export enum Types {
  CREATE_USER = 'CREATE_USER',
  LOGIN_USER = 'LOGIN_USER',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  CREATE_GROUP = 'CREATE_GROUP',
  FETCH_GROUPS = 'FETCH_GROUPS',
  DELETE_GROUPS = 'DELETE_GROUPS',
  CREATE_ORDER = 'CREATE_ORDER',
  FETCH_MY_ORDERS = 'FETCH_MY_ORDERS',
  FETCH_ORDER = 'FETCH_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER'
}
